/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jerome_jni_JNIProcess */

#ifndef _Included_com_jerome_jni_JNIProcess
#define _Included_com_jerome_jni_JNIProcess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jerome_jni_JNIProcess
 * Method:    getInfo
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jerome_jni_JNIProcess_getInfo
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_jerome_jni_JNIProcess
 * Method:    getReverseByte
 * Signature: (B)I
 */
JNIEXPORT jint JNICALL Java_com_jerome_jni_JNIProcess_getReverseByte
  (JNIEnv *, jclass, jbyte);

#ifdef __cplusplus
}
#endif
#endif
